### ISSUE TITLE
stuck on connect long time until failed - computer use

### ISSUE THREAD

**Issue by YanivHaliwa** [anthropics/claude-quickstarts#98] opened 2024-10-24 08:41 UTC
![image](https://github.com/user-attachments/assets/a3207753-7313-4f24-ad10-5cb353392b37)

**Comment by x5a** [comment] 2024-10-24 17:33
@YanivHaliwa this is most likely a duplicate of #42

**Closed as not planned by x5a** 2024-10-24 17:33 UTC
Labels: computer use
