### ISSUE TITLE
[computer use] Unable to run Docker App

### ISSUE THREAD

**Issue by samlimby** [anthropics/claude-quickstarts#97] opened 2024-10-24 05:12 UTC
When I run the the docker script in the terminal, I'm getting the below response (haven't included my API key - for obvious reasons - but I get the same response when I do input it). 

Is this something I'm doing wrong? 

```
Unable to find image 'ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest' locally
computer-use-demo-latest: Pulling from anthropics/anthropic-quickstarts

docker: failed commit on ref "layer-sha256:2885575cf6c991e0bbfc2d6b901a19e15386d43586a54fcaa2f0b2f845c911b3": commit failed: unexpected commit digest sha256:9b76e1d99e5b11cea56bb3d19c605a112402d892d68a6cc358cd8bf07486f119, expected sha256:2885575cf6c991e0bbfc2d6b901a19e15386d43586a54fcaa2f0b2f845c911b3: failed precondition.
```

**Comment by bmacer** [comment] 2024-10-24 05:49
You might try to flush the image with `rmi` and pull the image again with `pull`?

```
docker rmi ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
docker pull ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
```

**Comment by samlimby** [comment] 2024-10-24 07:27
Thanks for getting back to me! Unfortunately no luck with this, just going to post in the complete log for a bit more context: 

`docker run -e ANTHROPIC_API_KEY=APIKEY_here 
-v $HOME/.anthropic:/home/computeruse/.anthropic 
-p 5900:5900 
-p 8501:8501 
-p 6080:6080 
-p 8080:8080 
-it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
Unable to find image 'ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest' locally
computer-use-demo-latest: Pulling from anthropics/anthropic-quickstarts
2885575cf6c9: Pulling fs layer 
f7eaf35c1046: Pulling fs layer 
365ce9798d4e: Pulling fs layer 
d37c4689d89c: Pulling fs layer 
eb08495f9bb9: Pulling fs layer 
2885575cf6c9: Downloading  639.4MB/639.4MB
827e0e1ed441: Already exists 
18cb9658fe62: Downloading  178.3MB/262.9MB
5699d2b7eb4c: Already exists 
e4e53e7892db: Already exists 
f1d312d052f9: Already exists 
4f4fb700ef54: Already exists 
docker: failed commit on ref "layer-sha256:2885575cf6c991e0bbfc2d6b901a19e15386d43586a54fcaa2f0b2f845c911b3": commit failed: unexpected commit digest sha256:9b76e1d99e5b11cea56bb3d19c605a112402d892d68a6cc358cd8bf07486f119, expected sha256:2885575cf6c991e0bbfc2d6b901a19e15386d43586a54fcaa2f0b2f845c911b3: failed precondition.
See 'docker run --help'.`

**Comment by Rutwikdev** [comment] 2024-10-24 08:50
might be digest mismatch error  :
This issue could be caused by: a discrepancy between the image layer's metadata on the server side or corrupted image layer while downloading or outdated cache which doen't match the current version...
**Clear Docker's Image Cache :** `docker system prune -a`
**retry pulling the image** :`docker pull ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
`
Tip : Ensure you're running the latest version of Docker
 If the problem persists, it could be on the image hosting server's side. Check for any updates or issues with `ghcr.io.`

**Comment by x5a** [comment] 2024-10-24 18:01
@samlimby closing this out as this is an issue with either ghcr.io, your docker setup, or a network firewall/proxy that is potentially rewriting your requests. Thanks @bmacer / @Rutwikdev.

**Closed as not planned by x5a** 2024-10-24 18:01 UTC
Labels: computer use
