### ISSUE TITLE
crash on the code

### ISSUE THREAD

**Issue by epictz06** [anthropics/claude-quickstarts#136] opened 2024-10-29 15:59 UTC
Traceback (most recent call last):
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/computeruse/computer_use_demo/streamlit.py", line 384, in <module>
    asyncio.run(main())
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/computeruse/computer_use_demo/streamlit.py", line 214, in main
    st.session_state.messages = await sampling_loop(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/computer_use_demo/loop.py", line 165, in sampling_loop
    result = await tool_collection.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/computer_use_demo/tools/collection.py", line 32, in run
    return await tool(**tool_input)
                 ^^^^^^^^^^^^^^^^^^
TypeError: ComputerTool.__call__() missing 1 required keyword-only argument: 'action'

it try to open firefox and it thow the error

**Comment by p-i-** [comment] 2024-10-29 16:01
This is a duplicate of https://github.com/anthropics/anthropic-quickstarts/issues/135 which is literally the most recent issue. You should at least skim issues before posting one, else this pollutes.

**Comment by x5a** [comment] 2024-10-30 15:37
Caused by [this now resolved incident](https://status.anthropic.com/incidents/yf39k9sw8rqx).

**Closed as not planned** 2024-10-30 15:37 UTC
Labels: duplicate, computer use
